name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.10.1
  flare_flutter: ^2.0.6
  firebase_auth: ^0.18.3+1
  cloud_firestore: ^0.14.3+1
  firebase_core: ^0.5.2+1
  regexpattern: ^1.0.0
  audioplayers: ^0.17.0
  connectivity: ^2.0.2
  modal_progress_hud: ^0.1.3
  google_fonts: ^1.1.1
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - assets/
  - images/
  
